Desktop version/ Capstone-project-2
alexander16108/capstone-project-2 pull request #4
Opened 2021-07-06 14:27 UTC by alexander16108

## - Create Functatitives for the hamburger menu and button 

## - Implemented the Use of Sass in this project 

## - Commented as frequently as possible

2021-07-06 19:18 UTC, Shaher-11 requested changes
#### Hello @alexander16108,

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Add some space between the footer and the cards 
![wrong1](https://user-images.githubusercontent.com/58376020/124654929-79d37680-de9f-11eb-9990-10274951ac44.png)


- [ ] Check the comments below:point_down:


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 4 reviews remaining . If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

2021-07-06 19:18 UTC, Shaher-11 commented on README.md
> +- [live demo of this project](https://alexander16108.github.io/capstone-project-2/)
The live link is not working, please fix it

2021-07-06 19:18 UTC, Shaher-11 commented on assets/html/about.html
> +            </div>
the logo must be linked to the homepage

2021-07-06 19:18 UTC, Shaher-11 commented on assets/html/main.html
> +        </div>
the logo must be linked to the home page

2021-07-07 07:06 UTC, rloterh commented on README.md
> +- [live demo of this project](https://alexander16108.github.io/capstone-project-2/)
Well resolved.

2021-07-07 07:08 UTC, rloterh commented on assets/html/about.html
> +            </div>
Well resolved.

2021-07-07 07:12 UTC, rloterh commented on assets/html/main.html
> +        </div>
Well reolvesd.

2021-07-07 07:14 UTC, alexander16108 commented on README.md
> +- [live demo of this project](https://alexander16108.github.io/capstone-project-2/)
sorry i have no idea on how to solve that problem please could you help me out

2021-07-07 07:36 UTC, rloterh requested changes
Hi Alex, 

You did a good job for implementing changes requested by the previous reviewer 😄, you got most right!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there!👍 

## Required Changes ♻️
- [ ] _Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
__As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 3 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).__

2021-07-07 07:36 UTC, rloterh commented on README.md
> +- [live demo of this project](https://alexander16108.github.io/capstone-project-2)
- [ ] Your live demo link is displaying a ReadMe instead of the actual webpage. This issue is due to storing the `index.html` and `about.html` files inside the `assets/html` folder:
![image](https://user-images.githubusercontent.com/12745474/124716972-98b42600-defc-11eb-8f4e-4c001faa251d.png)

To ensure your demo site on GitHub pages is hosted correctly kindly move the `index.html` and the `main.html` files into the root directory of your project. Also, ensure that external css links in the html files are being pointed to correctly after the files are moved.

2021-07-07 07:36 UTC, rloterh commented on assets/html/about.html
> +######################################
- [ ] To ensure a cleaner code let's remove the **all** the comments in our code and **all** empty lines which do not serve any purpose.

2021-07-07 08:57 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @alexander16108, 

Good job on implementing the suggested changes. Well Done, Now I'm able to access the live link.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-06 19:19 UTC, merged